export const weather = [
    {       
        "name": "London",
        "conditions": {
            "description": "Cloudy with a chance of meatballs",
            "temp": 51,
            "feels_like": 53,
            "humidity": 83
        },
        "wind": {
          "speed": 1.2,
        },
        "Monday": {
            "eightAM": 46,
            "nineAM": 48,
            "tenAM": 48,
            "elevenAM": 50,
            "twelvePM": 52,
            "onePM": 52,
            "twoPM": 53,
            "threePM": 53,
            "fourPM": 52,
            "fivePM": 50,
            "sixPM": 48,
            "sevenPM": 48,
            "eightPM": 46,
        },
        "Tuesday": {
            "eightAM": 47,
            "nineAM": 49,
            "tenAM": 49,
            "elevenAM": 51,
            "twelvePM": 53,
            "onePM": 54,
            "twoPM": 55,
            "threePM": 55,
            "fourPM": 54,
            "fivePM": 54,
            "sixPM": 53,
            "sevenPM": 48,
            "eightPM": 46,
        },
        "Wednesday": {
            "eightAM": 45,
            "nineAM": 46,
            "tenAM": 46,
            "elevenAM": 47,
            "twelvePM": 48,
            "onePM": 48,
            "twoPM": 50,
            "threePM": 50,
            "fourPM": 50,
            "fivePM": 49,
            "sixPM": 48,
            "sevenPM": 48,
            "eightPM": 46,
        },
        "Thursday": {
            "eightAM": 42,
            "nineAM": 43,
            "tenAM": 44,
            "elevenAM": 44,
            "twelvePM": 46,
            "onePM": 46,
            "twoPM": 48,
            "threePM": 50,
            "fourPM": 50,
            "fivePM": 50,
            "sixPM": 48,
            "sevenPM": 48,
            "eightPM": 46,
        },
        "Friday": {
            "eightAM": 46,
            "nineAM": 48,
            "tenAM": 49,
            "elevenAM": 52,
            "twelvePM": 53,
            "onePM": 55,
            "twoPM": 56,
            "threePM": 54,
            "fourPM": 52,
            "fivePM": 50,
            "sixPM": 48,
            "sevenPM": 48,
            "eightPM": 46,
        },
        "Saturday": {
            "eightAM": 50,
            "nineAM": 51,
            "tenAM": 53,
            "elevenAM": 54,
            "twelvePM": 55,
            "onePM": 57,
            "twoPM": 55,
            "threePM": 55,
            "fourPM": 52,
            "fivePM": 51,
            "sixPM": 51,
            "sevenPM": 48,
            "eightPM": 46,
        },
        "Sunday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 60,
            "threePM": 56,
            "fourPM": 57,
            "fivePM": 58,
            "sixPM": 57,
            "sevenPM": 56,
            "eightPM": 55,
        },
        "forcast": [
            { 
            "day": "Monday",
            "high": 51,
            "low": 44,
            "conditions": "Partly Cloudy",
            },
            { 
            "day": "Tuesday",
            "high": 51,
            "low": 38,
            "conditions": "Overcast",
            },
            { 
            "day": "Wednesday",
            "high": 55,
            "low": 44,
            "conditions": "Overcast",
            },
            { 
            "day": "Thursday",
            "high": 53,
            "low": 41,
            "conditions": "Overcast",
            },
            { 
            "day": "Friday",
            "high": 55,
            "low": 46,
            "conditions": "Sunny",
            },
            { 
            "day": "Saturday",
            "high": 53,
            "low": 46,
            "conditions": "Rainy",
            },
            { 
            "day": "Sunday",
            "high": 54,
            "low": 47,
            "conditions": "Rainy",
            },
        ],
    },
    {       
        "name": "New York",
        "conditions": {
            "description": "Sunny with a slight breeze",
            "temp": 58,
            "feels_like": 57,
            "humidity": 34
        },
        "wind": {
          "speed": 3,
        },
        "Monday": {
            "eightAM": 56,
            "nineAM": 58,
            "tenAM": 58,
            "elevenAM": 60,
            "twelvePM": 62,
            "onePM": 62,
            "twoPM": 63,
            "threePM": 63,
            "fourPM": 62,
            "fivePM": 60,
            "sixPM": 68,
            "sevenPM": 68,
            "eightPM": 66,
        },
        "Tuesday": {
            "eightAM": 57,
            "nineAM": 59,
            "tenAM": 59,
            "elevenAM": 61,
            "twelvePM": 63,
            "onePM": 64,
            "twoPM": 65,
            "threePM": 65,
            "fourPM": 64,
            "fivePM": 64,
            "sixPM": 63,
            "sevenPM": 58,
            "eightPM": 56,
        },
        "Wednesday": {
            "eightAM": 55,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 57,
            "twelvePM": 58,
            "onePM": 58,
            "twoPM": 60,
            "threePM": 60,
            "fourPM": 60,
            "fivePM": 69,
            "sixPM": 68,
            "sevenPM": 58,
            "eightPM": 56,
        },
        "Thursday": {
            "eightAM": 52,
            "nineAM": 53,
            "tenAM": 54,
            "elevenAM": 54,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 58,
            "threePM": 60,
            "fourPM": 60,
            "fivePM": 60,
            "sixPM": 58,
            "sevenPM": 58,
            "eightPM": 56,
        },
        "Friday": {
            "eightAM": 56,
            "nineAM": 58,
            "tenAM": 59,
            "elevenAM": 62,
            "twelvePM": 63,
            "onePM": 65,
            "twoPM": 66,
            "threePM": 64,
            "fourPM": 62,
            "fivePM": 60,
            "sixPM": 58,
            "sevenPM": 58,
            "eightPM": 56,
        },
        "Saturday": {
            "eightAM": 60,
            "nineAM": 61,
            "tenAM": 63,
            "elevenAM": 64,
            "twelvePM": 65,
            "onePM": 67,
            "twoPM": 65,
            "threePM": 65,
            "fourPM": 62,
            "fivePM": 61,
            "sixPM": 61,
            "sevenPM": 58,
            "eightPM": 56,
        },
        "Sunday": {
            "eightAM": 64,
            "nineAM": 66,
            "tenAM": 66,
            "elevenAM": 66,
            "twelvePM": 66,
            "onePM": 66,
            "twoPM": 70,
            "threePM": 66,
            "fourPM": 67,
            "fivePM": 68,
            "sixPM": 67,
            "sevenPM": 66,
            "eightPM": 65,
        },
        "forcast": [
            { 
            "day": "Monday",
            "high": 58,
            "low": 37,
            "conditions": "Sunny",
            },
            { 
            "day": "Tuesday",
            "high": 59,
            "low": 42,
            "conditions": "Sunny",
            },
            { 
            "day": "Wednesday",
            "high": 58,
            "low": 42,
            "conditions": "Partly Cloudy",
            },
            { 
            "day": "Thursday",
            "high": 62,
            "low": 47,
            "conditions": "Partly Cloudy",
            },
            { 
            "day": "Friday",
            "high":61,
            "low": 49,
            "conditions": "Rain",
            },
            { 
            "day": "Saturday",
            "high": 57,
            "low": 53,
            "conditions": "Rain",
            },
            { 
            "day": "Sunday",
            "high": 64,
            "low": 47,
            "conditions": "Partly Cloudy",
            },
        ],
    },
    
    {       
        "name": "Los Angeles",
        "conditions": {
            "description": "Cloudy with a chance of meatballs",
            "temp": 70,
            "feels_like": 65,
            "humidity": 100
        },
        "wind": {
          "speed": 1.5,
        },
        "Monday": {
            "eightAM": 66,
            "nineAM": 68,
            "tenAM": 68,
            "elevenAM": 70,
            "twelvePM": 72,
            "onePM": 72,
            "twoPM": 73,
            "threePM": 73,
            "fourPM": 72,
            "fivePM": 70,
            "sixPM": 68,
            "sevenPM": 68,
            "eightPM": 66,
        },
        "Tuesday": {
            "eightAM": 67,
            "nineAM": 69,
            "tenAM": 69,
            "elevenAM": 71,
            "twelvePM": 73,
            "onePM": 74,
            "twoPM": 75,
            "threePM": 75,
            "fourPM": 74,
            "fivePM": 74,
            "sixPM": 73,
            "sevenPM": 68,
            "eightPM": 66,
        },
        "Wednesday": {
            "eightAM": 65,
            "nineAM": 66,
            "tenAM": 66,
            "elevenAM": 67,
            "twelvePM": 68,
            "onePM": 68,
            "twoPM": 70,
            "threePM": 70,
            "fourPM": 70,
            "fivePM": 69,
            "sixPM": 68,
            "sevenPM": 68,
            "eightPM": 66,
        },
        "Thursday": {
            "eightAM": 62,
            "nineAM": 63,
            "tenAM": 64,
            "elevenAM": 64,
            "twelvePM": 66,
            "onePM": 66,
            "twoPM": 68,
            "threePM": 70,
            "fourPM": 70,
            "fivePM": 70,
            "sixPM": 68,
            "sevenPM": 68,
            "eightPM": 66,
        },
        "Friday": {
            "eightAM": 66,
            "nineAM": 68,
            "tenAM": 69,
            "elevenAM": 72,
            "twelvePM": 73,
            "onePM": 75,
            "twoPM": 76,
            "threePM": 74,
            "fourPM": 72,
            "fivePM": 70,
            "sixPM": 68,
            "sevenPM": 68,
            "eightPM": 66,
        },
        "Saturday": {
            "eightAM": 70,
            "nineAM": 71,
            "tenAM": 73,
            "elevenAM": 74,
            "twelvePM": 75,
            "onePM": 77,
            "twoPM": 75,
            "threePM": 75,
            "fourPM": 72,
            "fivePM": 71,
            "sixPM": 71,
            "sevenPM": 68,
            "eightPM": 66,
        },
        "Sunday": {
            "eightAM": 74,
            "nineAM": 76,
            "tenAM": 76,
            "elevenAM": 76,
            "twelvePM": 76,
            "onePM": 76,
            "twoPM": 80,
            "threePM": 76,
            "fourPM": 77,
            "fivePM": 78,
            "sixPM": 77,
            "sevenPM": 76,
            "eightPM": 75,
        },
        "forcast": [
            { 
            "day": "Monday",
            "high": 69,
            "low": 48,
            "conditions": "Overcast",
            },
            { 
            "day": "Tuesday",
            "high": 70,
            "low": 46,
            "conditions": "Sunny",
            },
            { 
            "day": "Wednesday",
            "high": 70,
            "low": 48,
            "conditions": "Overcast",
            },
            { 
            "day": "Thursday",
            "high": 71,
            "low": 52,
            "conditions": "Sunny",
            },
            { 
            "day": "Friday",
            "high": 76,
            "low": 51,
            "conditions": "Sunny",
            },
            { 
            "day": "Saturday",
            "high": 67,
            "low": 49,
            "conditions": "Partly Cloudy",
            },
            { 
            "day": "Sunday",
            "high": 71,
            "low": 51,
            "conditions": "Sunny",
            },
        ],
    },

]