export const weather = [
    {       
        "name": "London",
        "conditions": {
            "description": "Cloudy with a chance of meatballs",
            "temp": 70,
            "feels_like": 65,
            "humidity": 100
        },
        "wind": {
          "speed": 1.5,
        },
        "Monday": {
            "eightAM": 35,
            "nineAM": 40,
            "tenAM": 45,
            "elevenAM": 50,
            "twelvePM": 60,
            "onePM": 70,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Tuesday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Wednesday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Thursday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Friday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Saturday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Sunday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "forcast": [
            { 
            "day": "Monday",
            "high": 1,
            "low": 2,
            "conditions": "sunny",
            },
            { 
            "day": "Tuesday",
            "high": 3,
            "low": 4,
            "conditions": "rainy",
            },
            { 
            "day": "Wednesday",
            "high": 5,
            "low": 6,
            "conditions": "cloudy",
            },
            { 
            "day": "Thursday",
            "high": 7,
            "low": 8,
            "conditions": "hot",
            },
            { 
            "day": "Friday",
            "high": 9,
            "low": 10,
            "conditions": "cold",
            },
            { 
            "day": "Saturday",
            "high": 11,
            "low": 12,
            "conditions": "windy",
            },
            { 
            "day": "Sunday",
            "high": 13,
            "low": 14,
            "conditions": "partly",
            },
        ],
    },

    {       
        "name": "New York",
        "conditions": {
            "description": "Raining cats and dogs",
            "temp": 60,
            "feels_like": 55,
            "humidity": 80
        },
        "wind": {
          "speed": 1.5,
        },
        "Monday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Tuesday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Wednesday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Thursday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Friday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Saturday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Sunday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "forcast": [
            { 
            "day": "Monday",
            "high": 11,
            "low": 22,
            "conditions": "sunny",

            },
            { 
            "day": "Tuesday",
            "high": 33,
            "low": 44,
            "conditions": "rainy",
            },
            { 
            "day": "Wednesday",
            "high": 55,
            "low": 66,
            "conditions": "cloudy",
            },
            { 
            "day": "Thursday",
            "high": 77,
            "low": 88,
            "conditions": "hot",
            },
            { 
            "day": "Friday",
            "high": 90,
            "low": 100,
            "conditions": "cold",
            },
            { 
            "day": "Saturday",
            "high": 111,
            "low": 122,
            "conditions": "windy",
            },
            { 
            "day": "Sunday",
            "high": 13,
            "low": 14,
            "conditions": "partly",
            },
        ],
    },
    
    {       
        "name": "Los Angeles",
        "conditions": {
            "description": "Cloudy with a chance of meatballs",
            "temp": 70,
            "feels_like": 65,
            "humidity": 100
        },
        "wind": {
          "speed": 1.5,
        },
        "Monday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Tuesday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Wednesday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Thursday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Friday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Saturday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "Sunday": {
            "eightAM": 24,
            "nineAM": 56,
            "tenAM": 56,
            "elevenAM": 56,
            "twelvePM": 56,
            "onePM": 56,
            "twoPM": 80,
            "threePM": 56,
            "fourPM": 56,
            "fivePM": 56,
            "sixPM": 56,
            "sevenPM": 56,
            "eightPM": 56,
        },
        "forcast": [
            { 
            "day": "Monday",
            "high": 1,
            "low": 2,
            "conditions": "sunny",
            },
            { 
            "day": "Tuesday",
            "high": 3,
            "low": 4,
            "conditions": "rainy",
            },
            { 
            "day": "Wednesday",
            "high": 5,
            "low": 6,
            "conditions": "cloudy",
            },
            { 
            "day": "Thursday",
            "high": 7,
            "low": 8,
            "conditions": "hot",
            },
            { 
            "day": "Friday",
            "high": 9,
            "low": 10,
            "conditions": "cold",
            },
            { 
            "day": "Saturday",
            "high": 11,
            "low": 12,
            "conditions": "windy",
            },
            { 
            "day": "Sunday",
            "high": 13,
            "low": 14,
            "conditions": "partly",
            },
        ],
    },

]